// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAccountTransactionsParams creates a new GetAccountTransactionsParams object
// with the default values initialized.
func NewGetAccountTransactionsParams() *GetAccountTransactionsParams {
	var ()
	return &GetAccountTransactionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccountTransactionsParamsWithTimeout creates a new GetAccountTransactionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAccountTransactionsParamsWithTimeout(timeout time.Duration) *GetAccountTransactionsParams {
	var ()
	return &GetAccountTransactionsParams{

		timeout: timeout,
	}
}

// NewGetAccountTransactionsParamsWithContext creates a new GetAccountTransactionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAccountTransactionsParamsWithContext(ctx context.Context) *GetAccountTransactionsParams {
	var ()
	return &GetAccountTransactionsParams{

		Context: ctx,
	}
}

// NewGetAccountTransactionsParamsWithHTTPClient creates a new GetAccountTransactionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAccountTransactionsParamsWithHTTPClient(client *http.Client) *GetAccountTransactionsParams {
	var ()
	return &GetAccountTransactionsParams{
		HTTPClient: client,
	}
}

/*GetAccountTransactionsParams contains all the parameters to send to the API endpoint
for the get account transactions operation typically these are written to a http.Request
*/
type GetAccountTransactionsParams struct {

	/*AccountID
	  Account identifier

	*/
	AccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get account transactions params
func (o *GetAccountTransactionsParams) WithTimeout(timeout time.Duration) *GetAccountTransactionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get account transactions params
func (o *GetAccountTransactionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get account transactions params
func (o *GetAccountTransactionsParams) WithContext(ctx context.Context) *GetAccountTransactionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get account transactions params
func (o *GetAccountTransactionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get account transactions params
func (o *GetAccountTransactionsParams) WithHTTPClient(client *http.Client) *GetAccountTransactionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get account transactions params
func (o *GetAccountTransactionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get account transactions params
func (o *GetAccountTransactionsParams) WithAccountID(accountID string) *GetAccountTransactionsParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get account transactions params
func (o *GetAccountTransactionsParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccountTransactionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
