// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDefaultBalanceAccountParams creates a new GetDefaultBalanceAccountParams object
// with the default values initialized.
func NewGetDefaultBalanceAccountParams() *GetDefaultBalanceAccountParams {

	return &GetDefaultBalanceAccountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDefaultBalanceAccountParamsWithTimeout creates a new GetDefaultBalanceAccountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDefaultBalanceAccountParamsWithTimeout(timeout time.Duration) *GetDefaultBalanceAccountParams {

	return &GetDefaultBalanceAccountParams{

		timeout: timeout,
	}
}

// NewGetDefaultBalanceAccountParamsWithContext creates a new GetDefaultBalanceAccountParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDefaultBalanceAccountParamsWithContext(ctx context.Context) *GetDefaultBalanceAccountParams {

	return &GetDefaultBalanceAccountParams{

		Context: ctx,
	}
}

// NewGetDefaultBalanceAccountParamsWithHTTPClient creates a new GetDefaultBalanceAccountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDefaultBalanceAccountParamsWithHTTPClient(client *http.Client) *GetDefaultBalanceAccountParams {

	return &GetDefaultBalanceAccountParams{
		HTTPClient: client,
	}
}

/*GetDefaultBalanceAccountParams contains all the parameters to send to the API endpoint
for the get default balance account operation typically these are written to a http.Request
*/
type GetDefaultBalanceAccountParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get default balance account params
func (o *GetDefaultBalanceAccountParams) WithTimeout(timeout time.Duration) *GetDefaultBalanceAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get default balance account params
func (o *GetDefaultBalanceAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get default balance account params
func (o *GetDefaultBalanceAccountParams) WithContext(ctx context.Context) *GetDefaultBalanceAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get default balance account params
func (o *GetDefaultBalanceAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get default balance account params
func (o *GetDefaultBalanceAccountParams) WithHTTPClient(client *http.Client) *GetDefaultBalanceAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get default balance account params
func (o *GetDefaultBalanceAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDefaultBalanceAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
